---
version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - /home/pi/nfsdocker-volumes:/config
    ports:
      - "1337:1337"
    restart: unless-stopped