version: "3.9"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    environment:
    - PUID=1000
    - PGID=1000
    ports:
    - 3000:3000
    volumes:
    - /home/pi/nfsdocker-volumes/grafana:/var/lib/grafana
    restart: unless-stopped


