version: "3"
services:
  matrix:
      image: matrixdotorg/synapse:latest
      container_name: matrix
      environment:
        - SYNAPSE_SERVER_NAME=matrix.0lzi.tk
        - SYNAPSE_REPORT_STATS=yes
      volumes:
        - /home/pi/nfsdocker-volumes/matrix:/data
      ports:
        - 8008:8008

      restart: unless-stopped