version: "3.9"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/pi/nfsdocker-volumes/nextcloud/config:/config
      - /home/pi/nfsdocker-volumes/nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TZ=Europe/London
    volumes:
      - /home/pi/nfsdocker-volumes/mariadb:/config
    restart: unless-stopped
