---
services:
  nextcloud:
    image: linuxserver/nextcloud:30.0.0
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - /home/oli/nfsdocker-volumes/nextcloud-new/config:/config
      - /home/oli/nfsdocker-volumes/nextcloud-new/data:/data
        #- /home/pi/nfsdocker-volumes/nextcloud-new/config:/config
        #- /home/pi/nfsdocker-volumes/nextcloud-new/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
    labels:
      - "diun.enable=true"
  mariadb:
    image: linuxserver/mariadb:10.11.6
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/London
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/oli/nfsdocker-volumes/mariadb-new:/config
        #- /home/pi/nfsdocker-volumes/mariadb-new:/config
    restart: unless-stopped
