name: diun

services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "~/nfsdocker-volumes/diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=${DIUN_WEBHOOK_URL}"
      - "DIUN_NOTIF_DISCORD_RENDERFIELDS=${DIUN_RENDER}"
      - "DIUN_NOTIF_DISCORD_TIMEOUT=${DIUN_TIMEOUT}"
      - "DIUN_NOTIF_DISCORD_TEMPLATEBODY=${DIUN_TEMPLATE}"
    labels:
      - "diun.enable=true"
    restart: always
