version: "2"
services:
   node-red:
     image: nodered/node-red:latest
     container_name: nodered
     environment:
       - TZ=Europe/London
       - PUID=1000
       - PGID=1000
     ports:
       - "1880:1880"
     volumes:
        - /home/pi/nfsdocker-volumes/nodered:/data
     restart: unless-stopped