version: "2"
services:
  letsencrypt:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    networks:
      - lsio
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=0lzi.tk
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=http
      - EXTRA_DOMAINS=${EXTRA_DOMAINS}
    volumes:
      - /home/pi/nfsdocker-volumes/letsencrypt:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
