---
version: "3.9"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
        - NET_ADMIN
    environment:
        - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-reload
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - URL=${URL}
        - SUBDOMAINS=${SUBDOMAINS}
        - VALIDATION=${VALIDATION}
        - EXTRA_DOMAINS=${EXTRA_DOMAINS}
    volumes:
      #  - /home/pi/docker-volumes/swag:/config
      #  - /home/pi/nfsdocker-volumes/swag:/config
        - /home/oli/nfsdocker-volumes/swag:/config

    ports:
        - 443:443
        - 80:80
        - 81:81
    restart: unless-stopped
