version: "2"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: proofhut
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=proofhut.co.uk
      - SUBDOMAINS=www
      - VALIDATION=http
    volumes:
      - /home/pi/docker-volumes/letsencrypt:/config
    ports:
      - 444:443
      - 81:80
    restart: unless-stopped
