---
version: "3.9"
services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/pi/nfsdocker-volumes/grav/config:/config
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped