---
version: "3.9"
services:
  portainer:
    image: portainer/agent:2.17.1
    container_name: portainer_agent
    environment:
      - EDGE=1 
      - EDGE_ID=$EDGE_ID1
      - EDGE_KEY=$EDGE_KEY1
      - CAP_HOST_MANAGEMENT=1 
      - EDGE_INSECURE_POLL=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/nfsdocker-volumes/portainer_agent:/var/lib/docker/volumes
      - /:/host 
      - /home/pi/nfsdocker-volumes/portainer_agent:/data 
    restart: unless-stopped
