version: "3"
services:
  portainer:
    image: portainer/agent
    container_name: portainer_agent
    environment:
      - EDGE=1 
      - EDGE_ID=$EDGE_ID
      - EDGE_KEY=$EDGE_KEY
      - CAP_HOST_MANAGEMENT=1 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/docker-volumes/portainer_agent:/var/lib/docker/volumes
      - /:/host 
      - /home/pi/docker-volumes/portainer_agent:/data 
    restart: unless-stopped