version: "3.9"
services:
  portainer:
    image: portainer/portainer-ee
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/nfsdocker-volumes/portainer/data:/data
    ports:
        - 8000:8000
        - 9000:9000
        - 9443:9443
    restart: unless-stopped
