---
version: "2"
services:
  ghost:
    image: ghost:4.48.8
    container_name: ghost
    environment:
      - url=https://blog.0lzi.com
      - mail__transport="SMTP"
      - mail__from=${GHOST_MAIL_FROM}
      - mail__options__service="SMTP"
      - mail__options__host=${MAIL_HOST}
      - mail__options__port="587"
      - mail__options__auth__user=${MAIL_AUTH}
      - mail__options__auth__pass=${MAIL_AUTH_PASS}
    volumes:
      - /home/kellyo/docker-volumes/ghost/content:/var/lib/ghost/content
    ports:
      - 2368:2368
    restart: unless-stopped

  letsencrypt:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=${SWAG_URL}
      - VALIDATION=http
    volumes:
      - /home/user/docker-volumes/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped