---
version: "3.9"
name: ddocbarber
services:
  demo-blog:
    image: ghost:4.48.8
    container_name: ddocbarber
    environment:
      - url=${URL_BARBER}
      - mail__transport="SMTP" 
      - mail__from=${BARBER_MAIL_FROM}
      - mail__options__service="SMTP" 
      - mail__options__host=${MAIL_HOST}
      - mail__options__port="587" 
      - mail__options__auth__user=${MAIL_AUTH}
      - mail__options__auth__pass=${MAIL_AUTH_PASS}
    volumes:
      - /home/oli/nfsdocker-volumes/ddocbarber/content:/var/lib/ghost/content
        # - /home/pi/nfsdocker-volumes/ddocbarber/content:/var/lib/ghost/content
    ports:
      - 3009:2368
    restart: unless-stopped
