---
version: "3.9"
name: ghost-blog
services:
  blog:
    image: ghost
    container_name: ghost-blog
    depends_on:
      - ghost-db
    environment:
      - url=${URL}
      - mail__transport="SMTP" 
      - mail__from=${GHOST_MAIL_FROM}
      - mail__options__service="SMTP" 
      - mail__options__host=${MAIL_HOST}
      - mail__options__port="587" 
      - mail__options__auth__user=${MAIL_AUTH}
      - mail__options__auth__pass=${MAIL_AUTH_PASS}
      - database__client = mysql
      - database__connection__host =  db
      - database__connection__user = root
      - database__connection__password = ${DB_PASS}
      - database__connection__database = ghost
    volumes:
      - /home/pi/nfsdocker-volumes/ghost-blog/content:/var/lib/ghost/content
    ports:
      - 3006:2368
    restart: unless-stopped
  
  ghost-db:
    image: mysql:8.0
    container_name: ghost-db
    environment:
      - MYSQL_ROOT_PASSWORD = ${DB_PASS}
    volumes:
      - /home/pi/nfsdocker/ghost-blog/db:/var/lib/mysql
    restart: always
