version: "3.9"
services:
  mythic-systems:
    image: ghost:4.48.8
    container_name: mythic-systems
    environment:
      - url=${URL_MS}
      - mail__transport="SMTP" 
      - mail__from=${MYTHIC_MAIL_FROM}
      - mail__options__service="SMTP" 
      - mail__options__host=${MAIL_HOST}
      - mail__options__port="587" 
      - mail__options__auth__user=${MAIL_AUTH}
      - mail__options__auth__pass=${MAIL_AUTH_PASS}
    volumes:
      - /home/pi/nfsdocker-volumes/mythic-systems/content:/var/lib/ghost/content
    ports:
      - 3003:2368
    restart: unless-stopped
