version: "2"
services:
    docghost:
    image: ghost
    container_name: olinx
    environment:
      - url=https://olinx.co.uk
    volumes:
      - /home/pi/docker-volumes/olinx/content:/var/lib/ghost/content
    ports:
      - 3002:2368
    restart: unless-stopped