version: "2"
services:
  ghost:
    image: ghost
    container_name: proofhut
    environment:
      - url=https://proofhut.co.uk
    volumes:
      - /home/pi/nfsdocker-volumes/ghost/content:/var/lib/ghost/content
    ports:
      - 3001:2368
    restart: unless-stopped