---
version: "3.9"
name: tolley
services:
  tolley:
    image: ghost:4.48.8
    container_name: tolley
    environment:
      - url=${URL_3D}
    volumes:
      - /home/oli/nfsdocker-volumes/tolley/content:/var/lib/ghost/content
        #- /home/pi/nfsdocker-volumes/tolley/content:/var/lib/ghost/content
    ports:
      - 3004:2368
    restart: unless-stopped
