---
version: '3.9'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /home/oli/nfsdocker-volumes/uptime-kuma-data:/app/data
        # - /home/pi/nfsdocker-volumes/uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
