version: "3.9"
services:
  minop:
    container_name: minio-server
    image:  quay.io/minio/minio
    volumes:
      - /home/pi/nfsdocker-volumes/minio:/data
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped