version: "3.9"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    environment:
    - INFLUXDB_HTTP_HTTPS_ENABLED=true
    - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/certificate.pem
    - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/etc/ssl/certificate.key
    ports:
    - 8086:8086
    volumes:
    - /home/pi/nfsdocker-volumes/influxdb:/var/lib/influxdb2
    - /home/pi/nfsdocker-volumes/influxdb/ssl:/etc/ssl/
    - /home/pi/nfsdocker-volumes/influxdb/data:/var/lib/influxdb2
    restart: unless-stopped


